### ISSUE TITLE
Android Pre-work: Todo App - Ready for Review

### ISSUE THREAD

**Issue by rswaroop** [rswaroop/ToDo#1]
My app's basic implementation with saving tasks to SQLite is complete. Please review and let me know your comments when you get a chance. /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Hi Swaroop,

Thanks for applying and submitting your pre-work. Based on your LinkedIn, your background indicates you have a significant amount of existing Android development experience. We appreciate you applying to participate, however our Android bootcamp is optimized for senior engineers without significant existing experience in Android.

Furthermore, since we have a limited number of seats, we like to optimize our impact by selecting people that have the most to benefit from participating. To be clear, those with significant Android experience can still benefit from the program but not as significantly as those that don't.

If you are interested in iOS development, you might enjoy applying to our [iOS bootcamp](http://codepath.com/iosbootcamp). Alternatively, let me know if you'd like access to the course self-paced as a remote observer so you can work on the projects on your own time.

Let me know if I have misunderstood your existing Android experience and thanks for your understanding.

**Comment by rswaroop** [comment]
Hi @nesquena,
Thanks for your response. It is absolutely amazing that you're looking at every detail of the application. You're right. I do have decent amount of Android experience. But, mostly it has been with non-UI and SDK development using Threads, Services, Broadcast receivers etc. The reason I applied for this bootcamp is to get hands-on experience with Views, Layouts, Fragments and learn more concepts that I already don't know.

I understand seats are limited. I'll be happy to get access to the course as a remote observer.

Thanks!

**Comment by nesquena** [comment]
Great, thanks for confirming. I have marked you down as a remote observer so you can learn self-paced with the course materials and project once the course begins alongside other observers. More details will follow closer to the class. In the meantime you may also enjoy reviewing our [comprehensive open-source Android Guides](http://guides.codepath.com/android#getting-started) for lots of resources and links to other Android courses and materials as well.
